name: Deploy

on: 
  push:
    branches: [ main ]

jobs:
  Build: #custom
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Create .env #custom
        run: echo 'PORT=${{secrets.PORT}}' > .env

      - name: Run build #custom
        run: docker-compose up -d