name: Deploy

on: 
  push:
    branches: [ main ]

jobs:
  Build: #custom
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Create custom .env file #custom
        run: |
          echo 'PORT=${{secrets.PORT}}' > .env
          echo 'DB_NAME=${{secrets.DB_NAME}}' > .env
          echo 'DB_USER=${{secrets.DB_USER}}' > .env
          echo 'DB_PASSWORD=${{secrets.DB_PASSWORD}}' > .env
          echo 'MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}' > .env

      - name: Run build #custom
        run: docker-compose up -d